[book]
authors = ["Tulir Asokan"]
language = "en"
multilingual = false
src = "."
title = "Meowlnir"
site-url = "/meowlnir/"

[build]
build-dir = "../dist/meowlnir"

[preprocessor.links]

[output.html]
git-repository-url = "https://github.com/mautrix/docs"
git-repository-icon = "fa-github"
additional-css = ["../bridges/additional.css"]
theme = "../theme/meowlnir"

[output.linkcheck]
optional = true
user-agent = "Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0"
cache-timeout = 604800
exclude = []
traverse-parent-directories = false
